### ISSUE TITLE
lando worker VMs are not mounting volume storage

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#80]
Launched a job with lando 0.5.0, and the job fails because the `/` partition fills up. On inspection, there is a /dev/vdb on the instance, but it is not mounted.

The cloud config should be partitioning and mounting this device, but it is not mounted.

**Comment by dleehr** [comment]
On the lando server, the `/etc/lando_config.yml` file has duplicate blocks. One is ansible-managed and the other is not.

```
work_queue:
  host: ...
  username: ...
  password: ...
  listen_queue: ...
  worker_username: ...
  worker_password: ...
vm_settings:
  worker_image_name: ...
  ssh_key_name: ...
  network_name: ...
  floating_ip_pool_name: ...
  default_flavor_name: ..."m1.small"
  cwl_base_command:
    - "cwltoil"
    - "--logDebug"
    - "--logFile"
    - "cwltoil.log"
    - "--workDir"
    - "/work/"
    - "--jobStore"
    - "/work/jobstore"
  volume_mounts:
    /dev/vdb1: /work
  
cloud_settings:
  auth_url: ...
  username: ...
  password: ...
  user_domain_name: ...
  project_domain_name: ...
bespin_api:
  url: ...
  token: ...
# BEGIN ANSIBLE MANAGED BLOCK
cwl_base_command: [u'cwltoil', u'--logDebug', u'--logFile', u'cwltoil.log', u'--workDir', u'/work/', u'--jobStore', u'/work/jobstore']
work_queue:
  host: ...
  username: ...
  password: ...
  listen_queue: ...
  worker_username: ...
  worker_password: ...
vm_settings:
  worker_image_name: ...
  ssh_key_name: ...
  network_name: ...
  floating_ip_pool_name: ...
  default_flavor_name: ...
cloud_settings:
  auth_url: ...
  username: ...
  password: ...
  user_domain_name: ...
  project_domain_name: ...
bespin_api:
  url: ...
  token: ...
# END ANSIBLE MANAGED BLOCK
```
